#pragma once

#include "/OceanShaders/Private/Complex.ush"
#include "/OceanShaders/Private/CoordinateToIndex.ush"

float Amplitude;
float PatchLength;
float Gravity;
float WindSpeed;
float2 WindDirection;

static const float Pi = 3.14159265358979323846f;

float2 CalculateK(uint2 Index)
{
    float kx = Pi * (2 * float(Index.x) - float(BufferSize.x)) / PatchLength;
    float ky = Pi * (2 * float(Index.y) - float(BufferSize.y)) / PatchLength;

	return float2(kx, ky);
}


