#include "/OceanShaders/Private/CoordinateToIndex.ush"

StructuredBuffer<float2> DataBuffer;
RWTexture2D<float4> OutputTexture;

[numthreads(THREADGROUPSIZE_X, THREADGROUPSIZE_Y, 1)]
void main(uint3 id : SV_DispatchThreadID)
{
    float Factor = 1 / float(BufferSize.x * BufferSize.y);
    
    float Value = clamp(DataBuffer[CoordinateToIndex(id.xy)].x * Factor, 0, 1);
    
    OutputTexture[id.xy] = float4(Value, Value, Value, 1);
}
